### ISSUE TITLE
特に修正箇所がない

### ISSUE THREAD

**Issue by ayaha401** [nkc-TakaoOnda/ZenjectTest#1]
特に修正箇所はなかった！
Issueって機能を一応説明すると

# タイトルを付けたり
こんな感じでタイトルをつけたり

# 修正を提案
https://github.com/nkc-TakaoOnda/ZenjectTest/blob/f6b3428ec9ca9b0055e2914f61c105283cc52fc6/ZenjectTest/Assets/Scripts/Move.cs#L8
ここのプログラム(リンクを押せばプログラムに飛べるよ)
```C#
// privateを明記、初期がnullなのを表記
[Inject] private IInputReceivable inputReceivable = null;
```

こんな感じでプログラムの修正するといい場所を分かりやすく表示したりできる。
今までみたいに会話だったりLINEとかでプログラム変更箇所を連絡し合ってるといつの間にか忘れたりってケースが起きるから今後はこの機能を使っていこうと思うよ。

この会話に対して返信ができるからやってみて

**Comment by nkc-TakaoOnda** [comment]
分かりやすいね

**Comment by ayaha401** [comment]
理解したみたいだから閉じますね
